// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8m4YHVphR3f3kl4UOu_u5gojEBLpUCl4',
    appId: '1:819123475747:web:11f5c66bb2550fc87a2896',
    messagingSenderId: '819123475747',
    projectId: 'safeheaven-d2d70',
    authDomain: 'safeheaven-d2d70.firebaseapp.com',
    storageBucket: 'safeheaven-d2d70.firebasestorage.app',
    measurementId: 'G-EVXZJTE6G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_jp-6uciasSSmMIwLQ9UJeJnr17xrT4',
    appId: '1:819123475747:android:73ebedb94f36b6277a2896',
    messagingSenderId: '819123475747',
    projectId: 'safeheaven-d2d70',
    storageBucket: 'safeheaven-d2d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq97x84lVupAkHRrTN2xngcuBog0HgyEE',
    appId: '1:819123475747:ios:073ccb609268b0957a2896',
    messagingSenderId: '819123475747',
    projectId: 'safeheaven-d2d70',
    storageBucket: 'safeheaven-d2d70.firebasestorage.app',
    iosBundleId: 'com.example.safeheaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq97x84lVupAkHRrTN2xngcuBog0HgyEE',
    appId: '1:819123475747:ios:073ccb609268b0957a2896',
    messagingSenderId: '819123475747',
    projectId: 'safeheaven-d2d70',
    storageBucket: 'safeheaven-d2d70.firebasestorage.app',
    iosBundleId: 'com.example.safeheaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8m4YHVphR3f3kl4UOu_u5gojEBLpUCl4',
    appId: '1:819123475747:web:ce8ba6cb1428010a7a2896',
    messagingSenderId: '819123475747',
    projectId: 'safeheaven-d2d70',
    authDomain: 'safeheaven-d2d70.firebaseapp.com',
    storageBucket: 'safeheaven-d2d70.firebasestorage.app',
    measurementId: 'G-LS4XK0PM5E',
  );
}
